### ISSUE TITLE
Dcli with Fish Shell

### ISSUE THREAD

**Issue by lohanidamodar** [bsutton/dcli#122]
**Is your feature request related to a problem? Please describe.**
Unable to use dcli with fish shell. I receive following error when i run `dcli create hello.dart`

```
Setting flag: verbose
DCli Version: 0.39.3
Found command Instance of 'CreateCommand'
env:  SHELL:/usr/bin/fish
env:  SHELL:/usr/bin/fish
UnimplementedError: UnimplementedError 
Stacktrace: unknown_shell.dart : UnknownShell.isSudo : 144
create.dart : CreateCommand.run : 30
command_line_runner.dart : CommandLineRunner.process : 86
entry_point.dart : EntryPoint._parseCmdLine : 37
entry_point.dart : EntryPoint.process : 31
dcli.dart : DCli.run : 11
dcli.dart : main : 6
isolate_patch.dart : _startIsolate.<anonymous closure> : 299
isolate_patch.dart : _RawReceivePortImpl._handleMessage : 168
```

**Describe the solution you'd like**
Looks like the fish shell is unimplemented. How can we implement fish shell

**Comment by shalva97** [comment]
same error on my Arch Linux KDE

**Comment by bsutton** [comment]
TIL there is  shell called fish:)

Adding shell support is fairly easy.

I would start by copying an existing shell library such as  lib/src/shell/zsh_shell.dart renaming it fish_shell.dart

Make any changes to fish_shell that are required. 

Then add it to the list of supported shells in shell_detect.dart.

The library bash_shell support tab completion in conjunction with bin/dcli_complete.dart. bash is the only shell that supports tab completion at this point. You can safely ignore this as its a nice to have or have a crack at doing it for fish.

Submit a PR.

**Comment by lohanidamodar** [comment]
@bsutton Fish doesn't have startScript (like .zshrc or .bashrc) it uses fish config file, what do I do there?

**Comment by bsutton** [comment]
This is used by your installer to insert path statements.

I will have a look at modifying the API to make it more flexible.

**Comment by bsutton** [comment]
I've provided some doco on implementing a shell for dcli.
https://bsutton.gitbook.io/dcli/contributing/implemention-support-for-a-shell
