### ISSUE TITLE
Error while running flutter test

### ISSUE THREAD

**Issue by xenSlayer** [bsutton/dcli#137]
/D:/Flutter/.pub-cache/hosted/pub.dartlang.org/dcli-1.0.9/lib/src/util/wait_for_ex.dart:2:8: Error: Not found: 'dart:cli'
import 'dart:cli' as cli;
       ^
/D:/Flutter/.pub-cache/hosted/pub.dartlang.org/dcli-1.0.9/lib/src/script/runner.dart:1:8: Error: Not found: 'dart:cli'
import 'dart:cli';
       ^
/D:/Flutter/.pub-cache/hosted/pub.dartlang.org/dcli-1.0.9/lib/src/util/wait_for_ex.dart:24:13: Error: Method not found: 'waitFor'.
    value = cli.waitFor<T>(future);
            ^^^^^^^
/D:/Flutter/.pub-cache/hosted/pub.dartlang.org/dcli-1.0.9/lib/src/script/runner.dart:31:21: Error: The method 'waitFor' isn't defined for the class 'ScriptRunner'.
 - 'ScriptRunner' is from 'package:dcli/src/script/runner.dart' ('/D:/Flutter/.pub-cache/hosted/pub.dartlang.org/dcli-1.0.9/lib/src/script/runner.dart').
Try correcting the name to the name of an existing method, or defining a method named 'waitFor'.
    final process = waitFor<Process>(Process.start(

**Comment by bsutton** [comment]
Dcli does not work with flutter.
