### ISSUE TITLE
help: permission error on read/copy/write attempt on directories

### ISSUE THREAD

**Issue by carlomigueldy** [bsutton/dcli#145]
I am receiving permission error whenever I try to read or copy directory from one to another.

![image](https://user-images.githubusercontent.com/45052332/119762687-bbf0bc00-bee0-11eb-85e0-b17b72ae7888.png)

`flutter doctor`
![image](https://user-images.githubusercontent.com/45052332/119762712-c9a64180-bee0-11eb-965b-27a7c839dff4.png)

Anyone got any ideas how I fix this up? I am using Git Bash terminal

**Comment by bsutton** [comment]
This doesn't appear to be a dcli related issue.

It simply looks like you don't have read privileges for the file in
question.

Only thought is 'app' and directory or a file?
If its a directory then read will always fail.

Have you tried running the query with 'Run as Administrator'?

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by carlomigueldy** [comment]
How do I "Run as Administrator"?

I am executing this command `./main.exe -b foobar`

**Comment by bsutton** [comment]
When you start the command prompt or powershell you there is an option 'Run
as Administrator'

https://www.digitalcitizen.life/run-as-admin/

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by carlomigueldy** [comment]
Hey man, I just resolved it

> If its a directory then read will always fail.

This got me thinking from your statement, so it works now!

Thanks man

**Comment by bsutton** [comment]
FYI: if you are trying to get a directory listing use the 'find' command.
