### ISSUE TITLE
implement dshell merge to aid with running vscode

### ISSUE THREAD

**Issue by bsutton** [bsutton/dcli#46]
For vscode to work it needs access to a pubsec.yam.

If we implement dshell merge/split a user can use this to easily make the pubspec accessible to vscode.

Need to ensure that split outputs the 'full' pubspec including the injected dependencies.

**Comment by brad-jones** [comment]
Not sure what your thinking here but could perhaps hook into: `onLanguage:dart` to _"split"_ the pubspec out into an actual file.

https://code.visualstudio.com/api/references/activation-events

Then figure out how https://github.com/emeraldwalk/vscode-runonsave works (or just use it) to execute the _"merge"_.

**Comment by bsutton** [comment]
interesting idea. At this point I've nearly completed work on a dshell command to do the merge/split

dshell merge xxx.script
dshell split xxx.script
I've just been distracted with some windows issues :)

**Comment by bsutton** [comment]
We no longer support virtual projects.
