### ISSUE TITLE
Can't install on my mac: /Users/merlyn/.bashrc does not exists

### ISSUE THREAD

**Issue by RandalSchwartz** [bsutton/dcli#48]
**Describe the bug**
failure at dshell install

**To Reproduce**
1. 'pub global activate dshell'
2. 'dshell install'
3. error '/Users/merlyn/.bashrc does not exists'

**Expected behavior**
I expected the install to continue to completion.

**Screenshots**

**Run dshell doctor:**
From the cli run `dshell doctor`
```
dshell doctor             
dshell: Expected a script name instead found: doctor

For help with dshell options:
  dshell help | help <command>
    Displays the usage message | Display the command's usage message.```


**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by bsutton** [comment]
Can you install the latest dev version and try again. I think I've fixed
this.

**Comment by RandalSchwartz** [comment]
How do I install "the latest dev version"?  Does that require cloning the github?  Or providing a different switch to activate?

**Comment by bsutton** [comment]
I've just released stable version with the changes.
So you just need to do a global activate again

pub global activate dshell

**Comment by bsutton** [comment]
Did you managed to get it installed?

**Comment by bsutton** [comment]
closing as I believe this is is now resolved. Please re-open if you are still having issues.
