### ISSUE TITLE
Upgrade to null saftey.

### ISSUE THREAD

**Issue by bsutton** [bsutton/dcli#93]
Need to wait until the 'test' package fully supports null saftey.

The recommendation is to wait for all dependencies to also support null safety.

**Comment by Wikiwix** [comment]
Add it as a comment here for now, as it is part of this issue:

* The now provided *nullsafe* release does use non-null-safe dependencies (at least for some there is a nullsafe version available).
* there is a typo in the version name: it currently is `nullsaftey` though it should be **`nullsafety`** 🙈 .

**Comment by bsutton** [comment]
And I thought IT was a safe place for people like me who can't spell :)

I've been working on releasing a full nnbd version.

I'm just waiting on two packages pubspec and sys_info.
I've pushed PR's for both of these so hopefully we will see these published in the next couple of days.

I've have about 10 unit tests to fix, but these all look like problems with mockit and nnbd which I believe I know how to fix.

So with any luck by the end of next week we will have a full release.

**Comment by Wikiwix** [comment]
IT is only as safe as the used linter / tool for static analysis (not only for spelling 🙃 …)

Ok, so I guess fingers crossed 🤞🏻 
Thanks for the effort :) 👍🏻

**Comment by bsutton** [comment]
I've released 0.50.1. There are a couple of minor packages that are still -null-safety but these shouldn't cause issues.

**Comment by bsutton** [comment]
completed.
